apiVersion: v1
kind: ConfigMap
metadata:
  name: streamingapp-config
  namespace: streamingapp
data:
  MONGO_URI: mongodb://mongodb:27017/streamingapp
  AWS_REGION: us-east-1

  CLIENT_URL: http://k8s-streamin-streamin-ca676dcfa1-477240795.us-east-1.elb.amazonaws.com

  CLIENT_URLS: http://k8s-streamin-streamin-ca676dcfa1-477240795.us-east-1.elb.amazonaws.com

  STREAMING_PUBLIC_URL: http://k8s-streamin-streamin-ca676dcfa1-477240795.us-east-1.elb.amazonaws.com