apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.mongodb.port | default 27017 }}
      targetPort: 27017
      name: mongodb
  selector:
    app: mongodb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: mongodb
  replicas: {{ .Values.replicaCount.mongodb }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: 27017
              name: mongodb
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.storage.existingClaim }}